CREATE TABLE ROOT."USER" (
	ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	STREET VARCHAR(100),
	ZIP_CODE VARCHAR(5),
	CITY VARCHAR(50)
);


CREATE TABLE ROOT.PRODUCT (
	CODE VARCHAR(50) NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	PRICE NUMERIC(19,6) NOT NULL,
	STOCK INTEGER NOT NULL DEFAULT 0
);


INSERT INTO ROOT.PRODUCT VALUES ('T1', 'Tee Shirt', 55.6, 12);
INSERT INTO ROOT.PRODUCT VALUES ('C2', 'Cle USB', 9.5, 45);
INSERT INTO ROOT.PRODUCT VALUES ('S3', 'Stylo', 3.7, 34);
INSERT INTO ROOT.PRODUCT VALUES ('C4', 'Calculatrice', 20.0, 4);